// Get all persons
GET http://localhost:3001/api/persons

###

// Get single person with id 1
GET http://localhost:3001/api/persons/1

###

// Get single person with (non-existing) id 100
GET http://localhost:3001/api/persons/100

###

// Delete a person with id 1
DELETE http://localhost:3001/api/persons/1

###

// Post new person
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Uusi henkilö",
    "number": "123-456798765"
}


###

// Get info
GET http://localhost:3001/info
