@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}

###
// Get all persons
GET {{host}}/api/persons

###
// Get single person with id 1
GET {{host}}/api/persons/1

###
// Get single person with (non-existing) id 100
GET {{host}}/api/persons/100

###
// Delete a person with id 1
DELETE {{host}}/api/persons/1

###
// Post new person
POST {{host}}/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Uusi henkilö",
    "number": "123-456798765"
}

###
// Get info
GET {{host}}/info
